import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useAuthStore from '../store/authStore'
import PostGrid from '../components/PostGrid';
import React, { useState, useEffect } from 'react';
import { collection, query, where, onSnapshot } from 'firebase/firestore';
import { db, auth } from "../firebase/firebase.config";
import { useFirestoreQueryData } from "@react-query-firebase/firestore";



export default function Home() {

  const { userProfile, addUser, userDetails, addUserDets } = useAuthStore();


  useEffect(() => {
    if (userProfile) {
      const dbRef = collection(db, "users")
      const q = query(dbRef, where("useruid", "==", `${userProfile.uid}`))


      onSnapshot(q, snap => {
        if (!snap.empty) {
          const data = snap.docs[0].data();
          addUserDets(data)
        } else {
          console.log("No user found with given id")
        }
      })
    }
  }, [userProfile])





  const [posts, setPosts] = useState([]);


  const ref = query(collection(db, "posts"));
  // Provide the query to the hook
  const data = useFirestoreQueryData(["posts"], ref, {
    subscribe: true,
  });




  if (data.isLoading) {
    return <div>Loading...</div>;
  }

  const snapshot = data.data;



  return (


    <div className='w-full  '>


      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <PostGrid posts={snapshot} />



    </div>
  )
}
